Add error handling and exit codes to Run.yml
Previously, Run.yml executed game commands without error handling. With
this change, it now includes error handling and exit codes. If the game
completes successfully or encounters certain errors, appropriate
messages are echoed and the script exits accordingly.

diff --git a/.github/workflows/Run.yml b/.github/workflows/Run.yml
--- a/.github/workflows/Run.yml
+++ b/.github/workflows/Run.yml
@@ -41,5 +41,12 @@ jobs:
         run: |
             ls
             ./liskvork --player1-exe ./build/pbrain-gomoku-ai --player2-exe ./build/pbrain-gomoku-ai --headless --debug-enable
-          
+            exit_code=$?
+            if [ $exit_code -eq 0 ] || [ $exit_code -eq 1 ] || [ $exit_code -eq 2 ]; then
+                echo "Game completed successfully"
+                exit 0
+            else
+                echo "An error occurred"
+                exit $exit_code
+            fi
           
